### ISSUE TITLE
Trigger commands on entering a state

### ISSUE THREAD

**Issue by breathbath** [Metabor/Statemachine-Example#3]
I have a simple use case:
1) Order is in state new
2) I trigger "shipment event"
3) In the condition I check if the order has necessary delivery info if it doesn't I go to "waiting for delivery info" state, if it does I go to "shipped" state. 
4) Then on "added delivery info" event I go to shipped state if the delivery info is valid
The problem is that I want to send a notification email to the user once order goes to shipped state. If I assign command to "shipment event" then sending will be triggered for both transitions - from new to shipped and from new to waiting for delivery info so I need to check in the command if the order has delivery info or not. But on the graph I see that the command of "sending email" is assigned to the transition new->waiting.. with condition "not delivery info provided" which is a little bit confusing for the end user.
I can use an intermediate state "executing sending email" but still in the case when the delivery info is not valid, the command will be triggered (from the state "waiting for delivery info"). 
It would be nice to have a possibility to trigger some commands on entering a state or how would you solve the described case?

Second problem - I didn't find the way to describe the solutions path. If I want to see, why an order landed in some state, I need to implement some logging for every command, but still won't see the whole route. Is there a way of doing it?

Thanks in advance.

**Comment by Metabor** [comment]
In other projects I solved this problems by adding an "onEnter" event, that the statemachine is triggering by itself when a status is changed.
You can add this Observer to your statemachine:
https://github.com/Metabor/Statemachine/blob/master/src/Metabor/Statemachine/Observer/OnEnterObserver.php
that will do the job.
Now you only have to add the "sending email" command to the event "onEnter" on the "shipped" state. I you use the graph thing to display your process you have to add a transition from "shipped" to "shipped" with the event "onEnter" otherwise you will not see it in the graph (is some known problem).
You can use the SetupHelper in the dev-master (or version 1.13 which will be the next version) to do this more easy:
https://github.com/Metabor/Statemachine/blob/master/src/Metabor/Statemachine/Util/SetupHelper.php
Only put your Process in the contructor and use the helper functions (that works with strings/names only and handle adding states if not existing).

For your second question. I don't know how your stateful object looks like but you can either add the logging of the state changes to the setter of the current state or what is more generic write an Observer for logging and add this to your statemachine. The statemachine will call it on each status change. Examples on Observers can be found here:
https://github.com/Metabor/Statemachine/tree/master/src/Metabor/Statemachine/Observer

I hope I could help you (otherwise feel free to reopen this ticket).
Also other questions are allways welcome.

**Comment by breathbath** [comment]
Thanks for answering:
another question is how would you resolve timeouts of orders in the current sm design?

**Comment by Metabor** [comment]
You can add a Transition to the target State after timeout with EventName NULL and Condition:
https://github.com/Metabor/Statemachine/blob/master/src/Metabor/Statemachine/Condition/Timeout.php
Your stateful class should implement LastStateHasChangedDateInterface or overwrite the getLastStateHasChangedDate() method from the condition if the date should be get in a different way.

This is actually only in master. You can also use version "~1.1.3" which will be the next version.

**Comment by breathbath** [comment]
If there is no event for the timeout resolving how should I trigger the statemachine for that with order context?

**Comment by Metabor** [comment]
For Transitions, that only have a Condition without Event you have to use
checkTransition().
In the actual project I am working on, we use Condition-Only Transitions not only for timeouts, but also for complete checks and other checks.
This is an example how I generic checker could look like (this could be called by cronjob):

``` php
        $stateNames = array();
        foreach ($processDetector->getProcessNames() as $processName) {
            $process = $processDetector->getProcess($processName);
            $states = new FilterStateByTransition($process->getStates());
            foreach ($states as $state) {
                $stateName = $state->getName();
                $stateNames[$stateName] = $stateName;
            }
        }
        if (!empty($stateNames)) {
            $subjects = $repository->findBy(array('currentStateName' => $stateNames));
            $output->writeln('Check ' . count($subjects));

            foreach ($subjects as $subject) {
                    $statemachine = $statemachineFactory->createStatemachine($subject);
                    $statemachine->checkTransitions();
            }
        }
```

If you only have timeouts as conditions, your subjects are in DB and you need to handle many subjects fast, you should save the next timeout \DateTime into DB (or NULL if there is no timeout) every time a status change (can be done with a statemachine observer like setting the status is done). In this way you can more easily and faster grab all the subjects that have to be checked.
The timeout can be calculated by grabbing all the Transitions and check them for TimeOutCondition and get the \DateIntervall to be used from there.

I hope this example and the description helps you to handle your status timeouts.

**Comment by breathbath** [comment]
By the way there is some typing inconsistency in the SetupHelper:
constructor requires StateCollectionInterface but every public method implicitly calls findOrCreateState which is dependant on StateCollection class and it fails if none is provided. So this means that you actually require StateCollection rather than StateCollectionInterface what in my opinion violates LSP.
I was actually trying to make an easy setup for a Process instance but failed because of this!

**Comment by Metabor** [comment]
Thanks for the hint.
The Reason was, that you can use the SetupHelper (which is optional and not part of MetaborStd) with any StateCollection that implements the StateCollectionInterface, but then you have to make sure that it has all the needed States in the Collection.
If you want to add them on-the-fly (what makes totally sense), and you want to use your own StateCollectionInterface you only need to overwrite this method and you can still use SetupHelper with all the other logic that is implemented there.
If SetupHelper would be part of MetaborStd, then there would be some StateAdderHelper Interface, that will do this job and SetupHelper then would delegate to this class.
But my choice was the more simpler way of changing the SetupHelper, because it is only an AddOn that can be optionally used and makes setting up processes more easy. There is no dependency to SetupHelper from anywhere else.

**Comment by breathbath** [comment]
To be honest for me it's not obvious how to use setup helper. The obvious way was for me to have a "nice" interface for defining transitions to make code more readable but at the end I just implemented helper functions in the Process itself)

**Comment by Metabor** [comment]
And this is also a good way to set it up and the way I have also done it before I added the SetupHelper. :)

**Comment by breathbath** [comment]
Just discovered another use case for which I didn't find a solution:
- we trigger event "createOrder", if it looks suspicious it goes to "verify" state, if order is ok it goes to "waiting for payment".
- "verify" state can be entered from other states e.g. if payment provider requires additional verification
- now we want to trigger a command (email notification to a security manager) only if the order goes from "new" to "verify" on "createOrder" event
- with the current implementation if I assign this command to "createOrder" event it will be triggered also for non "suspicious" 
- if I assign this command to "onEnter" event by entering the "verify" state it will be triggered for other transitions to this state e.g. if payment provider requires some verification, but for this case I don't want to notify the security manager as it should handle only the new orders.
- the only place I could do it is the condition but this is not the right place for it as I won't see this command/execution on the graph and it breaks also SRP of Condition interface.

How would you solve this problem? Thanks!

**Comment by Metabor** [comment]
I would put a technical state (that is only needed for modelling and is not part of the business-process) in between. It will look like this:

Transition from "new" to "waiting for "payment" with Event "createOrder" and Condition "order is ok"
Transition from "new" to "waiting to send XY mail" with Event "createOrder" and Condition "looks suspicious"
Transition from "waiting to send XY mail" to "verify" with Event "onEnter"
Command at "waiting to send XY mail" with Event "onEnter"

Or if the "verify" when the Order "looks suspicious" and the one if payment provider requires additional verification has not the same meaning, you can also split it into 2 different states.

Hint: 
I don't know if you use the default TransitionSelector:
https://github.com/Metabor/Statemachine/blob/master/src/Metabor/Statemachine/Factory/TransitionSelector/OneOrNoneActiveTransition.php
or this one, that can also be used:
https://github.com/Metabor/Statemachine/blob/master/src/Metabor/Statemachine/Factory/TransitionSelector/ScoreTransition.php

In the default one you have to model your conditions like this:
Transition from A to B with Event E and Condition "b"
Transition from A to C with Event E and Condition "not b"
So that never two Rules on outgoing Transitions are true at the same time

With the other you have different groups of transitions rules that are ranked.
Highest rank has a Transition with Event and Condition
Second rank has a Transition with only Event
Third rank has a Transition with only Condition
Lowest rank has a Transition without Event and without Condition

I all of this four groups still only one Transitions should be active (rules are true) at the same time, but there could also be active Transtitions in other of this 4 groups.

This make it possible to Model something like If-ELSEIF-ELSE.
Transition from A to B with Event E and Condition "b"
Transition from A to C with Event E

So if Event E is triggered and Condition b is true it will go to B. In all other cases (ELSE) it will go to C.
This also helps if you have more then two Transitions with different Conditions so you don't have to model for the ELSE-Part "not a and not b and not c".

I hope this helps modelling your process.
If you need additional help I am sometimes in Berlin, so we can also meet there (normally I work near U Oranienburger Tor and U Stadtmitte).
